version: '3'

networks:

  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:

  redis-cluster:
    image: redis:6
    command: redis-cli --cluster create 10.0.0.11:6379 10.0.0.12:6379 10.0.0.13:6379 10.0.0.14:6379 10.0.0.15:6379 10.0.0.16:6379 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      redisnet:
        ipv4_address: 10.0.0.2

  redis-1:
    build: ./redis
    image: redis-cluster-node
    networks:
      redisnet:
        ipv4_address: 10.0.0.11
    ports:
      - 6379:6379

  redis-2:
    image: redis-cluster-node
    networks:
      redisnet:
        ipv4_address: 10.0.0.12
    ports:
      - 6380:6379

  redis-3:
    image: redis-cluster-node
    networks:
      redisnet:
        ipv4_address: 10.0.0.13
    ports:
      - 6381:6379

  redis-4:
    image: redis-cluster-node
    networks:
      redisnet:
        ipv4_address: 10.0.0.14
    ports:
      - 6382:6379

  redis-5:
    image: redis-cluster-node
    networks:
      redisnet:
        ipv4_address: 10.0.0.15
    ports:
      - 6383:6379

  redis-6:
    image: redis-cluster-node
    networks:
      redisnet:
        ipv4_address: 10.0.0.16
    ports:
      - 6384:6379
